config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :tracksegment
  attr_accessor :description, :elevation, :latitude, :longitude, :name, :point_created_at
end

app/models/track.rb
class Track < ApplicationRecord
	attr_accessor :name, :gpx  
  	has_many :tracksegments, :dependent => :destroy
  	has_many :points, :through => :tracksegments
  	has_attached_file :gpx
end

app/models/tracksegment.rb
class Tracksegment < ApplicationRecord
  belongs_to :track
  has_many :points, :dependent => :destroy
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  		<%= yield %>	
  	</div>
  </body>
</html>

app/views/tracks/_form.html.erb
<%= form_for @track, :html => { :class => "form-horizontal track" } do |f| %>

  <% if @track.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @track.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%#=  <%=f.error_span(:name) %> 
  </div>
  <div class="form-group">
    <%= f.label :gpx_file_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :gpx_file_name, :class => 'form-control' %>
    </div>
    <%#= <%=f.error_span(:gpx_file_name) %>
  </div>
  <div class="form-group">
    <%= f.label :gpx_content_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :gpx_content_type, :class => 'form-control' %>
    </div>
    <%#= <%=f.error_span(:gpx_content_type) %>
  </div>
  <div class="form-group">
    <%= f.label :gpx_file_size, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :gpx_file_size, :class => 'form-control' %>
    </div>
    <%#= <%=f.error_span(:gpx_file_size) %>
  </div>
  <div class="form-group">
    <%= f.label :gpx_updated_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :gpx_updated_at, :class => 'form-control' %>
    </div>
    <%#= <%=f.error_span(:gpx_updated_at) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tracks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tracks/edit.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tracks/index.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:gpx_file_name) %></th>
      <th><%= model_class.human_attribute_name(:gpx_content_type) %></th>
      <th><%= model_class.human_attribute_name(:gpx_file_size) %></th>
      <th><%= model_class.human_attribute_name(:gpx_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= link_to track.id, track_path(track) %></td>
        <td><%= track.name %></td>
        <td><%= track.gpx_file_name %></td>
        <td><%= track.gpx_content_type %></td>
        <td><%= track.gpx_file_size %></td>
        <td><%= track.gpx_updated_at %></td>
        <td><%=l track.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      track_path(track), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_track_path(track), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      track_path(track),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_track_path,
            :class => 'btn btn-primary' %>

app/views/tracks/new.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tracks/show.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @track.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_file_name) %>:</strong></dt>
  <dd><%= @track.gpx_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_content_type) %>:</strong></dt>
  <dd><%= @track.gpx_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_file_size) %>:</strong></dt>
  <dd><%= @track.gpx_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_updated_at) %>:</strong></dt>
  <dd><%= @track.gpx_updated_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tracks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_track_path(@track), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              track_path(@track),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>